#pragma once

#define ALARM_WIFI_SSID "YOUR_WIFI_SSID"
#define ALARM_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define ALARM_MQTT_HOST "YOUR_MQTT_BROKER_HOST"
#define ALARM_MQTT_PORT 1883
#define ALARM_MQTT_USERNAME "device-client"
#define ALARM_MQTT_PASSWORD "YOUR_MQTT_PASSWORD"
